package com.servelet.hibernateproject;

public class Stringreverse {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		StringBuffer s=new StringBuffer("Manoj");
		s.reverse();
	System.out.println(s);
//		StringBuffer org=s;
//		String rev="";
//		for(int i=s.length()-1;i>=0;i--)
//		{
//			System.out.print(s.charAt(i));
//			rev=rev+s.charAt(i);
//		}
//		
//		//System.out.println(rev);
//		System.out.println();
//		if(org.equals(rev))
//		{
//			System.out.println("given string IS PALINDROME ");
//		}else
//			{
//			System.out.println("not a palindrome");
//			}

	}

}
//kavyashreen.ABCDEFGHIJKLMNOPQRSTUVWXYZ...... 
//KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
//VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
//YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
//RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
//
//
//JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
//UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
//NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
//GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
//KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
//OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
//OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
//KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
//
//
//GNG OUT
//YOYOOO
//KODSTHINI
//ELLA
//HMMM
//SARI
//AAAPICHHH
//CHESTAAAA
//PHONE CHAIIII
//HMM
//HMM
//KERA KITHOYTHAVEEE
//NALENE
//20000.....?
//		ADEEE
//		AGATHE
//REPLAY?????
//		*MAKA KELSA IRATHE BARI DOVEGALLU.....KOBBU*
//		SHISTUUU
//		ALLA HUDGUR ATHRANEEE E RANGE GE NULKOND MATHADTHIRALLA....HUDGIR ATHRA HENG MATHADALLA??????
//				BEKAGILLA